spring:
  application:
    name: feignClient

server:
  port: 8080


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    demo.IUserService: debug

